"""
data_pipeline/craft_catalog.py
==============================
Structured domain catalog of authentic Indian handicraft traditions,
grounded in official records (Development Commissioner for Handicrafts,
GI Registry, TRIFED, State Emporiums).

Contains verified combinations of:
- craft
- state
- region
- district
- product_types with realistic dimensions, weights, labor requirements,
  materials, traditional techniques, cost parameters, and price anchors.
"""

from __future__ import annotations

CRAFT_CATALOG = [
    {
        "craft": "Blue Pottery",
        "state": "Rajasthan",
        "region": "Marwar/Dhundhar",
        "district": "Jaipur",
        "source_id": "SRC-STATE-01",
        "source_reference": "Rajasthali & GI Registry (GI-4)",
        "products": [
            {
                "product_type": "Decorative Vase",
                "material": "Quartz Powder and Glass Paste",
                "technique": "Turquoise Glazing and Mould Casting",
                "length_cm": (12.0, 28.0),
                "width_cm": (12.0, 28.0),
                "height_cm": (20.0, 45.0),
                "weight_kg": (0.8, 3.2),
                "labor_days": (2.0, 6.0),
                "base_complexity": 6.0,
                "material_cost_range": (350, 950),
                "anchor_price_range": (1100, 3800),
                "demand_score": 7.5,
                "seasonality_score": 6.0,
            },
            {
                "product_type": "Wall Plate",
                "material": "Quartz Powder and Fuller's Earth",
                "technique": "Hand-painted Glazed Ceramic",
                "length_cm": (20.0, 35.0),
                "width_cm": (20.0, 35.0),
                "height_cm": (3.0, 5.0),
                "weight_kg": (0.5, 1.8),
                "labor_days": (1.5, 4.0),
                "base_complexity": 5.5,
                "material_cost_range": (250, 600),
                "anchor_price_range": (850, 2400),
                "demand_score": 8.0,
                "seasonality_score": 5.5,
            },
            {
                "product_type": "Planter",
                "material": "Quartz Powder and Multani Mitti",
                "technique": "Low-fire Oxide Painting",
                "length_cm": (15.0, 30.0),
                "width_cm": (15.0, 30.0),
                "height_cm": (15.0, 32.0),
                "weight_kg": (1.2, 4.0),
                "labor_days": (2.0, 5.0),
                "base_complexity": 5.0,
                "material_cost_range": (300, 800),
                "anchor_price_range": (950, 2900),
                "demand_score": 7.0,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Tea Coaster Set",
                "material": "Quartz Paste and Ceramic Glaze",
                "technique": "Fired Glaze Tile Painting",
                "length_cm": (10.0, 12.0),
                "width_cm": (10.0, 12.0),
                "height_cm": (0.8, 1.5),
                "weight_kg": (0.3, 0.7),
                "labor_days": (0.8, 2.0),
                "base_complexity": 4.0,
                "material_cost_range": (150, 350),
                "anchor_price_range": (450, 1200),
                "demand_score": 8.5,
                "seasonality_score": 6.5,
            },
        ],
    },
    {
        "craft": "Madhubani Painting",
        "state": "Bihar",
        "region": "Mithila",
        "district": "Madhubani",
        "source_id": "SRC-GOI-04",
        "source_reference": "GI Registry of India (GI-105) & DC (Handicrafts)",
        "products": [
            {
                "product_type": "Wall Art Painting",
                "material": "Handmade Paper and Natural Pigments",
                "technique": "Kachni Fine Line and Bharni Fill",
                "length_cm": (30.0, 90.0),
                "width_cm": (22.0, 60.0),
                "height_cm": (0.1, 0.5),
                "weight_kg": (0.1, 0.6),
                "labor_days": (3.0, 14.0),
                "base_complexity": 8.0,
                "material_cost_range": (200, 750),
                "anchor_price_range": (1400, 8500),
                "demand_score": 8.5,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Tussar Silk Dupatta",
                "material": "Tussar Silk Fabric and Natural Dyes",
                "technique": "Nib and Twig Freehand Painting",
                "length_cm": (220.0, 250.0),
                "width_cm": (80.0, 100.0),
                "height_cm": (0.1, 0.2),
                "weight_kg": (0.2, 0.4),
                "labor_days": (5.0, 16.0),
                "base_complexity": 8.5,
                "material_cost_range": (1100, 2400),
                "anchor_price_range": (3200, 12500),
                "demand_score": 8.0,
                "seasonality_score": 8.0,
            },
            {
                "product_type": "Framed Canvas Art",
                "material": "Cotton Canvas and Acrylic Pigment",
                "technique": "Godna and Tantrik Motifs",
                "length_cm": (45.0, 120.0),
                "width_cm": (30.0, 90.0),
                "height_cm": (2.5, 4.0),
                "weight_kg": (1.0, 3.5),
                "labor_days": (6.0, 22.0),
                "base_complexity": 8.8,
                "material_cost_range": (800, 2200),
                "anchor_price_range": (3800, 18000),
                "demand_score": 7.5,
                "seasonality_score": 6.5,
            },
        ],
    },
    {
        "craft": "Warli Painting",
        "state": "Maharashtra",
        "region": "Konkan",
        "district": "Palghar",
        "source_id": "SRC-GOI-01",
        "source_reference": "DC (Handicrafts) & TRIFED Tribal Catalog",
        "products": [
            {
                "product_type": "Mud-base Wall Panel",
                "material": "Cow Dung Mud Plaster and Rice Paste",
                "technique": "Bamboo Stick Geometric Figuration",
                "length_cm": (30.0, 75.0),
                "width_cm": (25.0, 60.0),
                "height_cm": (1.5, 3.0),
                "weight_kg": (0.8, 2.5),
                "labor_days": (1.5, 6.0),
                "base_complexity": 5.5,
                "material_cost_range": (150, 450),
                "anchor_price_range": (800, 3200),
                "demand_score": 7.0,
                "seasonality_score": 5.0,
            },
            {
                "product_type": "Handmade Paper Scroll",
                "material": "Handmade Paper and Rice White Pigment",
                "technique": "Tarpa Dance Ritual Painting",
                "length_cm": (40.0, 100.0),
                "width_cm": (20.0, 45.0),
                "height_cm": (0.1, 0.3),
                "weight_kg": (0.1, 0.4),
                "labor_days": (1.0, 4.0),
                "base_complexity": 5.0,
                "material_cost_range": (100, 300),
                "anchor_price_range": (600, 2200),
                "demand_score": 7.5,
                "seasonality_score": 5.5,
            },
            {
                "product_type": "Terracotta Pot Decor",
                "material": "Terracotta and Water-based White Oxide",
                "technique": "Circular Village Life Pictography",
                "length_cm": (15.0, 28.0),
                "width_cm": (15.0, 28.0),
                "height_cm": (18.0, 35.0),
                "weight_kg": (0.9, 2.8),
                "labor_days": (1.0, 3.5),
                "base_complexity": 4.8,
                "material_cost_range": (120, 350),
                "anchor_price_range": (550, 1800),
                "demand_score": 7.0,
                "seasonality_score": 6.0,
            },
        ],
    },
    {
        "craft": "Pattachitra",
        "state": "Odisha",
        "region": "Coastal Odisha",
        "district": "Puri",
        "source_id": "SRC-STATE-04",
        "source_reference": "Utkalika & Raghurajpur Heritage Village Documentation",
        "products": [
            {
                "product_type": "Palm Leaf Engraving (Tala Pattachitra)",
                "material": "Dried Palm Leaf and Lampblack Ink",
                "technique": "Iron Stylus Etching and Folding Ribbons",
                "length_cm": (25.0, 75.0),
                "width_cm": (15.0, 45.0),
                "height_cm": (0.5, 1.2),
                "weight_kg": (0.2, 0.8),
                "labor_days": (4.0, 18.0),
                "base_complexity": 9.0,
                "material_cost_range": (300, 850),
                "anchor_price_range": (1800, 11500),
                "demand_score": 8.0,
                "seasonality_score": 6.5,
            },
            {
                "product_type": "Cloth Scroll Painting",
                "material": "Cotton Cloth with Chalk Tamarind Paste",
                "technique": "Natural Mineral and Vegetable Pigment Painting",
                "length_cm": (45.0, 150.0),
                "width_cm": (30.0, 90.0),
                "height_cm": (0.2, 0.5),
                "weight_kg": (0.3, 1.2),
                "labor_days": (5.0, 24.0),
                "base_complexity": 8.8,
                "material_cost_range": (400, 1400),
                "anchor_price_range": (2500, 16000),
                "demand_score": 8.2,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Painted Coconut Shell",
                "material": "Polished Coconut Shell and Stone Colours",
                "technique": "Miniature Pattachitra Iconography",
                "length_cm": (10.0, 15.0),
                "width_cm": (10.0, 15.0),
                "height_cm": (10.0, 16.0),
                "weight_kg": (0.2, 0.5),
                "labor_days": (1.5, 4.0),
                "base_complexity": 6.5,
                "material_cost_range": (80, 220),
                "anchor_price_range": (550, 1850),
                "demand_score": 7.5,
                "seasonality_score": 6.0,
            },
        ],
    },
    {
        "craft": "Kalamkari",
        "state": "Andhra Pradesh",
        "region": "Rayalaseema/Coastal Andhra",
        "district": "Tirupati",
        "source_id": "SRC-GOI-01",
        "source_reference": "Srikalahasti Kalamkari GI-19 & DC (Handicrafts)",
        "products": [
            {
                "product_type": "Hand-painted Temple Hanging",
                "material": "Cotton Fabric and Natural Madder Dyes",
                "technique": "Bamboo Pen (Kalam) Freehand Drawing",
                "length_cm": (90.0, 240.0),
                "width_cm": (60.0, 150.0),
                "height_cm": (0.1, 0.3),
                "weight_kg": (0.4, 1.6),
                "labor_days": (6.0, 25.0),
                "base_complexity": 8.5,
                "material_cost_range": (600, 2200),
                "anchor_price_range": (2800, 18500),
                "demand_score": 7.8,
                "seasonality_score": 6.5,
            },
            {
                "product_type": "Silk Cotton Saree",
                "material": "Chanderi Silk-Cotton Blend and Natural Alum Dyes",
                "technique": "23-Step Hand-drawn and Washed Dyeing",
                "length_cm": (550.0, 630.0),
                "width_cm": (110.0, 120.0),
                "height_cm": (0.1, 0.2),
                "weight_kg": (0.5, 0.8),
                "labor_days": (7.0, 20.0),
                "base_complexity": 8.7,
                "material_cost_range": (1800, 4200),
                "anchor_price_range": (5200, 19500),
                "demand_score": 8.5,
                "seasonality_score": 8.5,
            },
            {
                "product_type": "Cushion Cover Pair",
                "material": "Cotton Sheeting and Natural Indigo/Myrobalan",
                "technique": "Kalam Drawing with Resist Dyeing",
                "length_cm": (40.0, 45.0),
                "width_cm": (40.0, 45.0),
                "height_cm": (1.0, 2.0),
                "weight_kg": (0.2, 0.4),
                "labor_days": (1.5, 3.5),
                "base_complexity": 6.0,
                "material_cost_range": (250, 550),
                "anchor_price_range": (850, 2200),
                "demand_score": 8.0,
                "seasonality_score": 6.0,
            },
        ],
    },
    {
        "craft": "Tanjore Painting",
        "state": "Tamil Nadu",
        "region": "Cauvery Delta",
        "district": "Thanjavur",
        "source_id": "SRC-STATE-03",
        "source_reference": "Poompuhar & Thanjavur Paintings GI-32",
        "products": [
            {
                "product_type": "Iconic Devotional Wall Art",
                "material": "Teakwood Board, 22K Gold Foil, Semi-precious Stones",
                "technique": "Gesso Relief Work with Real Gold Leaf Embossing",
                "length_cm": (25.0, 75.0),
                "width_cm": (20.0, 60.0),
                "height_cm": (4.0, 8.0),
                "weight_kg": (2.5, 12.0),
                "labor_days": (7.0, 30.0),
                "base_complexity": 9.2,
                "material_cost_range": (2500, 14000),
                "anchor_price_range": (7500, 55000),
                "demand_score": 8.2,
                "seasonality_score": 9.0,
            },
            {
                "product_type": "Miniature Pooja Frame",
                "material": "Chettinad Teak Frame and 22K Gold Foil",
                "technique": "Traditional Jaipur Gem Inlay and Gesso Relief",
                "length_cm": (15.0, 25.0),
                "width_cm": (12.0, 20.0),
                "height_cm": (3.0, 5.0),
                "weight_kg": (1.0, 2.8),
                "labor_days": (4.0, 10.0),
                "base_complexity": 8.0,
                "material_cost_range": (1400, 3800),
                "anchor_price_range": (4200, 14500),
                "demand_score": 8.5,
                "seasonality_score": 8.5,
            },
        ],
    },
    {
        "craft": "Phulkari",
        "state": "Punjab",
        "region": "Malwa/Majha",
        "district": "Patiala",
        "source_id": "SRC-GOI-01",
        "source_reference": "DC (Handicrafts) & Punjab Phulkari GI-170",
        "products": [
            {
                "product_type": "Bagh Bridal Dupatta",
                "material": "Khaddar Cotton Fabric and Untwisted Pat Silk Thread",
                "technique": "Darning Stitch Surface Geometry on Reverse",
                "length_cm": (220.0, 250.0),
                "width_cm": (100.0, 120.0),
                "height_cm": (0.2, 0.4),
                "weight_kg": (0.5, 0.9),
                "labor_days": (15.0, 45.0),
                "base_complexity": 8.8,
                "material_cost_range": (1200, 2800),
                "anchor_price_range": (4800, 19500),
                "demand_score": 8.0,
                "seasonality_score": 9.0,
            },
            {
                "product_type": "Phulkari Stole",
                "material": "Chanderi Silk-Cotton and Floss Silk",
                "technique": "Chope and Subhar Geometric Motifs",
                "length_cm": (180.0, 200.0),
                "width_cm": (55.0, 70.0),
                "height_cm": (0.1, 0.3),
                "weight_kg": (0.2, 0.4),
                "labor_days": (4.0, 10.0),
                "base_complexity": 7.0,
                "material_cost_range": (600, 1400),
                "anchor_price_range": (1800, 5200),
                "demand_score": 8.5,
                "seasonality_score": 8.0,
            },
            {
                "product_type": "Embroidered Jacket",
                "material": "Raw Silk and Multicolor Pat Thread",
                "technique": "Heavy Geometric Phulkari Needlework",
                "length_cm": (60.0, 75.0),
                "width_cm": (45.0, 55.0),
                "height_cm": (1.0, 2.0),
                "weight_kg": (0.4, 0.7),
                "labor_days": (6.0, 18.0),
                "base_complexity": 7.8,
                "material_cost_range": (900, 2200),
                "anchor_price_range": (2900, 9500),
                "demand_score": 7.5,
                "seasonality_score": 8.5,
            },
        ],
    },
    {
        "craft": "Chikankari",
        "state": "Uttar Pradesh",
        "region": "Awadh",
        "district": "Lucknow",
        "source_id": "SRC-GOI-04",
        "source_reference": "Lucknow Chikan GI-119 & DC (Handicrafts)",
        "products": [
            {
                "product_type": "Pure Georgette Kurta",
                "material": "Pure Viscose Georgette and Cotton Floss",
                "technique": "Bakhiya (Shadow), Tepchi, and Phanda Stitches",
                "length_cm": (105.0, 120.0),
                "width_cm": (50.0, 65.0),
                "height_cm": (0.2, 0.5),
                "weight_kg": (0.25, 0.45),
                "labor_days": (4.0, 18.0),
                "base_complexity": 8.2,
                "material_cost_range": (850, 2400),
                "anchor_price_range": (2600, 11500),
                "demand_score": 9.0,
                "seasonality_score": 7.5,
            },
            {
                "product_type": "Cotton Anarkali Suit Set",
                "material": "Mulmul Muslin Cotton and Mukaish Metal Badla",
                "technique": "Jaali, Murri, and Mukaish Hand Embroidery",
                "length_cm": (125.0, 140.0),
                "width_cm": (55.0, 75.0),
                "height_cm": (0.3, 0.8),
                "weight_kg": (0.4, 0.8),
                "labor_days": (8.0, 30.0),
                "base_complexity": 9.0,
                "material_cost_range": (1400, 3800),
                "anchor_price_range": (4500, 19500),
                "demand_score": 8.8,
                "seasonality_score": 8.0,
            },
            {
                "product_type": "Handmade Table Linen Set",
                "material": "Casement Cotton Fabric",
                "technique": "Cutwork Jaali and Floral Tepchi",
                "length_cm": (150.0, 225.0),
                "width_cm": (120.0, 150.0),
                "height_cm": (0.2, 0.4),
                "weight_kg": (0.6, 1.2),
                "labor_days": (5.0, 14.0),
                "base_complexity": 7.0,
                "material_cost_range": (650, 1600),
                "anchor_price_range": (2100, 6800),
                "demand_score": 7.2,
                "seasonality_score": 6.5,
            },
        ],
    },
    {
        "craft": "Kantha",
        "state": "West Bengal",
        "region": "Rarh/Birbhum",
        "district": "Birbhum",
        "source_id": "SRC-GOI-01",
        "source_reference": "Bengal Kantha GI-127 & DC (Handicrafts)",
        "products": [
            {
                "product_type": "Bishnupur Silk Kantha Saree",
                "material": "Murshidabad Silk and Silk Threads",
                "technique": "Running Stitch Narrative Folk Embroidery",
                "length_cm": (550.0, 630.0),
                "width_cm": (110.0, 120.0),
                "height_cm": (0.1, 0.3),
                "weight_kg": (0.45, 0.75),
                "labor_days": (10.0, 35.0),
                "base_complexity": 8.9,
                "material_cost_range": (2200, 5500),
                "anchor_price_range": (6500, 26000),
                "demand_score": 8.5,
                "seasonality_score": 8.0,
            },
            {
                "product_type": "Kantha Bedspread (Nakshi Kantha)",
                "material": "Layered Cotton Sheeting and Fast Cotton Thread",
                "technique": "Quilted Mandala and Lotus Motif Stitches",
                "length_cm": (220.0, 270.0),
                "width_cm": (180.0, 240.0),
                "height_cm": (0.5, 1.0),
                "weight_kg": (1.4, 2.6),
                "labor_days": (12.0, 40.0),
                "base_complexity": 8.6,
                "material_cost_range": (1100, 2800),
                "anchor_price_range": (3800, 16500),
                "demand_score": 8.0,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Embroidered Silk Stole",
                "material": "Tussar Silk and Multicolor Threads",
                "technique": "Paisley and Fish Pattern Running Stitches",
                "length_cm": (180.0, 210.0),
                "width_cm": (55.0, 70.0),
                "height_cm": (0.1, 0.2),
                "weight_kg": (0.15, 0.3),
                "labor_days": (3.0, 9.0),
                "base_complexity": 6.8,
                "material_cost_range": (550, 1300),
                "anchor_price_range": (1600, 4900),
                "demand_score": 8.3,
                "seasonality_score": 7.5,
            },
        ],
    },
    {
        "craft": "Dhokra",
        "state": "Chhattisgarh",
        "region": "Bastar",
        "district": "Bastar",
        "source_id": "SRC-GOI-03",
        "source_reference": "Bastar Dhokra GI-83 & TRIFED Catalog",
        "products": [
            {
                "product_type": "Tribal Figurine / Musician",
                "material": "Scrap Brass, Clay Core, and Natural Beeswax",
                "technique": "Lost-Wax (Cire Perdue) Bell Metal Casting",
                "length_cm": (10.0, 25.0),
                "width_cm": (8.0, 18.0),
                "height_cm": (15.0, 40.0),
                "weight_kg": (0.6, 2.8),
                "labor_days": (3.0, 10.0),
                "base_complexity": 7.8,
                "material_cost_range": (350, 1200),
                "anchor_price_range": (1200, 5400),
                "demand_score": 8.0,
                "seasonality_score": 6.0,
            },
            {
                "product_type": "Bullock Cart Sculpture",
                "material": "Brass Alloy and Rice Husk Residue",
                "technique": "Fine Wax Threadwork and Open Hearth Casting",
                "length_cm": (20.0, 45.0),
                "width_cm": (12.0, 25.0),
                "height_cm": (14.0, 32.0),
                "weight_kg": (1.5, 6.0),
                "labor_days": (5.0, 16.0),
                "base_complexity": 8.5,
                "material_cost_range": (850, 2800),
                "anchor_price_range": (2800, 11500),
                "demand_score": 7.5,
                "seasonality_score": 6.5,
            },
            {
                "product_type": "Diyas and Oil Lamp Set",
                "material": "Bell Metal / Brass Alloy",
                "technique": "Ornate Wax Filigree Moulding",
                "length_cm": (10.0, 20.0),
                "width_cm": (10.0, 20.0),
                "height_cm": (10.0, 25.0),
                "weight_kg": (0.4, 1.8),
                "labor_days": (2.0, 6.0),
                "base_complexity": 6.8,
                "material_cost_range": (250, 850),
                "anchor_price_range": (850, 3400),
                "demand_score": 8.5,
                "seasonality_score": 9.5,
            },
        ],
    },
    {
        "craft": "Bidriware",
        "state": "Karnataka",
        "region": "Kalyana-Karnataka",
        "district": "Bidar",
        "source_id": "SRC-STATE-02",
        "source_reference": "Cauvery Handicrafts & Bidriware GI-11",
        "products": [
            {
                "product_type": "Silver Inlaid Vase (Aftaba)",
                "material": "Zinc-Copper Alloy and Pure Silver Wire",
                "technique": "Tarkashi Inlay and Soil Oxidisation",
                "length_cm": (10.0, 22.0),
                "width_cm": (10.0, 22.0),
                "height_cm": (18.0, 38.0),
                "weight_kg": (0.9, 3.2),
                "labor_days": (4.0, 14.0),
                "base_complexity": 8.8,
                "material_cost_range": (900, 3400),
                "anchor_price_range": (3200, 14000),
                "demand_score": 7.8,
                "seasonality_score": 6.5,
            },
            {
                "product_type": "Decorative Plate",
                "material": "Non-ferrous Alloy and Pure Silver Sheet",
                "technique": "Tehnishan (Sheet Inlay) and Black Patina",
                "length_cm": (18.0, 35.0),
                "width_cm": (18.0, 35.0),
                "height_cm": (2.0, 4.0),
                "weight_kg": (0.6, 2.2),
                "labor_days": (3.0, 10.0),
                "base_complexity": 8.2,
                "material_cost_range": (700, 2400),
                "anchor_price_range": (2400, 9800),
                "demand_score": 8.0,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Jewellery Box",
                "material": "Zinc-Copper Casting and Fine Silver Inlay",
                "technique": "Zarnishan and Mehtabi Engraving",
                "length_cm": (12.0, 20.0),
                "width_cm": (8.0, 14.0),
                "height_cm": (5.0, 10.0),
                "weight_kg": (0.5, 1.6),
                "labor_days": (3.0, 8.0),
                "base_complexity": 7.9,
                "material_cost_range": (600, 1800),
                "anchor_price_range": (1950, 7200),
                "demand_score": 8.4,
                "seasonality_score": 7.5,
            },
        ],
    },
    {
        "craft": "Channapatna Toys",
        "state": "Karnataka",
        "region": "Old Mysore",
        "district": "Ramanagara",
        "source_id": "SRC-STATE-02",
        "source_reference": "Cauvery Handicrafts & Channapatna Toys GI-3",
        "products": [
            {
                "product_type": "Rocking Horse / Vehicle Toy",
                "material": "Wrightia Tinctoria (Ivory Wood) and Vegetable Lacquer",
                "technique": "Lathe Woodturning and Hand-applied Lac Dye",
                "length_cm": (15.0, 35.0),
                "width_cm": (8.0, 16.0),
                "height_cm": (12.0, 28.0),
                "weight_kg": (0.3, 1.4),
                "labor_days": (0.5, 2.5),
                "base_complexity": 4.5,
                "material_cost_range": (120, 400),
                "anchor_price_range": (450, 1600),
                "demand_score": 8.8,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Educational Stacking Rings",
                "material": "Aale Mara Wood and Non-toxic Natural Pigments",
                "technique": "Concentric Lathe Turning and Friction Polishing",
                "length_cm": (10.0, 15.0),
                "width_cm": (10.0, 15.0),
                "height_cm": (15.0, 26.0),
                "weight_kg": (0.25, 0.8),
                "labor_days": (0.4, 1.8),
                "base_complexity": 4.0,
                "material_cost_range": (100, 300),
                "anchor_price_range": (350, 1200),
                "demand_score": 9.0,
                "seasonality_score": 6.5,
            },
            {
                "product_type": "Decorative Wooden Peg Dolls",
                "material": "Seasoned Hale Wood and Lac Finish",
                "technique": "Screw-fitting Lathe Turning",
                "length_cm": (6.0, 10.0),
                "width_cm": (6.0, 10.0),
                "height_cm": (12.0, 22.0),
                "weight_kg": (0.2, 0.6),
                "labor_days": (0.5, 2.0),
                "base_complexity": 4.2,
                "material_cost_range": (90, 260),
                "anchor_price_range": (320, 1100),
                "demand_score": 8.5,
                "seasonality_score": 7.0,
            },
        ],
    },
    {
        "craft": "Terracotta",
        "state": "West Bengal",
        "region": "Rarh",
        "district": "Bankura",
        "source_id": "SRC-GOI-04",
        "source_reference": "Bankura Horse GI-133 & CCIC Catalog",
        "products": [
            {
                "product_type": "Bankura Long-eared Horse",
                "material": "Alluvial Clay and Rice Husk Ash",
                "technique": "Hollow Clay Wheel Throwing and Assemblage",
                "length_cm": (15.0, 45.0),
                "width_cm": (8.0, 22.0),
                "height_cm": (25.0, 90.0),
                "weight_kg": (0.8, 7.5),
                "labor_days": (1.5, 6.0),
                "base_complexity": 6.2,
                "material_cost_range": (120, 600),
                "anchor_price_range": (650, 3800),
                "demand_score": 8.2,
                "seasonality_score": 6.0,
            },
            {
                "product_type": "Terracotta Wall Relief Tile",
                "material": "Refined Terracotta Red Clay",
                "technique": "Intaglio Carving and Traditional Wood Kiln Firing",
                "length_cm": (20.0, 45.0),
                "width_cm": (20.0, 45.0),
                "height_cm": (2.5, 5.0),
                "weight_kg": (1.2, 4.2),
                "labor_days": (1.2, 4.0),
                "base_complexity": 5.8,
                "material_cost_range": (100, 400),
                "anchor_price_range": (500, 2200),
                "demand_score": 7.5,
                "seasonality_score": 5.5,
            },
        ],
    },
    {
        "craft": "Bastar Art",
        "state": "Chhattisgarh",
        "region": "Bastar",
        "district": "Kondagaon",
        "source_id": "SRC-GOI-03",
        "source_reference": "Bastar Wooden & Iron Crafts GI-84 & TRIFED",
        "products": [
            {
                "product_type": "Wrought Iron Wall Hanging / Mask",
                "material": "Recycled Scrap Iron and Charcoal",
                "technique": "Traditional Anvil Hammering and Chisel Beating",
                "length_cm": (20.0, 60.0),
                "width_cm": (15.0, 40.0),
                "height_cm": (3.0, 8.0),
                "weight_kg": (1.0, 4.5),
                "labor_days": (2.0, 7.0),
                "base_complexity": 6.8,
                "material_cost_range": (250, 800),
                "anchor_price_range": (950, 3800),
                "demand_score": 7.5,
                "seasonality_score": 6.0,
            },
            {
                "product_type": "Tribal Deepa Candlestand",
                "material": "Forged Wrought Iron",
                "technique": "Punched and Riveted Blacksmithing",
                "length_cm": (15.0, 30.0),
                "width_cm": (15.0, 30.0),
                "height_cm": (25.0, 65.0),
                "weight_kg": (1.2, 5.0),
                "labor_days": (2.5, 8.0),
                "base_complexity": 7.0,
                "material_cost_range": (300, 950),
                "anchor_price_range": (1100, 4400),
                "demand_score": 8.0,
                "seasonality_score": 7.5,
            },
        ],
    },
    {
        "craft": "Rajasthani Block Printing",
        "state": "Rajasthan",
        "region": "Dhundhar",
        "district": "Jaipur",
        "source_id": "SRC-STATE-01",
        "source_reference": "Rajasthali & Sanganeri Hand Block Print GI-121",
        "products": [
            {
                "product_type": "Cotton Bed Cover (King)",
                "material": "100% Cambric Cotton and Vegetable/Discharge Dyes",
                "technique": "Multi-color Hand Block Wooden Stamp Print",
                "length_cm": (250.0, 275.0),
                "width_cm": (220.0, 250.0),
                "height_cm": (0.2, 0.4),
                "weight_kg": (1.1, 1.8),
                "labor_days": (2.5, 7.0),
                "base_complexity": 6.5,
                "material_cost_range": (650, 1500),
                "anchor_price_range": (1750, 5200),
                "demand_score": 9.0,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Pure Cotton Voile Saree",
                "material": "Fine Mulmul Cotton and Natural Alizarin",
                "technique": "Bagru Syahi-Begar and Dabu Mud-Resist Print",
                "length_cm": (550.0, 630.0),
                "width_cm": (110.0, 118.0),
                "height_cm": (0.1, 0.2),
                "weight_kg": (0.35, 0.55),
                "labor_days": (2.0, 6.0),
                "base_complexity": 6.8,
                "material_cost_range": (500, 1200),
                "anchor_price_range": (1450, 4200),
                "demand_score": 9.2,
                "seasonality_score": 8.0,
            },
            {
                "product_type": "Table Runner Set",
                "material": "Cotton Duck Canvas and Eco-friendly Dyes",
                "technique": "Precision Sanganeri Floral Buta Block Print",
                "length_cm": (150.0, 180.0),
                "width_cm": (35.0, 45.0),
                "height_cm": (0.2, 0.4),
                "weight_kg": (0.3, 0.6),
                "labor_days": (1.0, 3.0),
                "base_complexity": 5.2,
                "material_cost_range": (200, 480),
                "anchor_price_range": (650, 1850),
                "demand_score": 8.4,
                "seasonality_score": 6.5,
            },
        ],
    },
    {
        "craft": "Ajrakh",
        "state": "Gujarat",
        "region": "Kutch",
        "district": "Kutch",
        "source_id": "SRC-GOI-04",
        "source_reference": "Kutch Ajrakh GI-810 & Craft Council of India",
        "products": [
            {
                "product_type": "Modal Silk Stole",
                "material": "Modal Silk Fabric, Indigo, Madder, Harda",
                "technique": "16-Stage Double-sided Resist Block Print",
                "length_cm": (180.0, 220.0),
                "width_cm": (55.0, 75.0),
                "height_cm": (0.1, 0.2),
                "weight_kg": (0.15, 0.3),
                "labor_days": (4.0, 12.0),
                "base_complexity": 8.4,
                "material_cost_range": (650, 1600),
                "anchor_price_range": (2100, 6500),
                "demand_score": 8.8,
                "seasonality_score": 7.5,
            },
            {
                "product_type": "Mashru Silk Saree",
                "material": "Mashru (Silk-Cotton Handloom) and Natural Indigo",
                "technique": "Gajji Geometrical Symmetrical Resist Printing",
                "length_cm": (550.0, 630.0),
                "width_cm": (110.0, 120.0),
                "height_cm": (0.1, 0.3),
                "weight_kg": (0.5, 0.8),
                "labor_days": (8.0, 22.0),
                "base_complexity": 9.0,
                "material_cost_range": (2400, 5800),
                "anchor_price_range": (6800, 24000),
                "demand_score": 8.5,
                "seasonality_score": 8.0,
            },
        ],
    },
    {
        "craft": "Kutch Embroidery",
        "state": "Gujarat",
        "region": "Kutch",
        "district": "Kutch",
        "source_id": "SRC-GOI-04",
        "source_reference": "Kutch Embroidery GI-37 & Qasab Kutch Craft",
        "products": [
            {
                "product_type": "Embroidered Toran / Wall Hanging",
                "material": "Cotton Base, Silk Threads, Tiny Shisha Mirrors",
                "technique": "Ahir and Rabari Chain Stitch with Mirror Work",
                "length_cm": (90.0, 150.0),
                "width_cm": (25.0, 45.0),
                "height_cm": (0.5, 1.2),
                "weight_kg": (0.4, 1.1),
                "labor_days": (5.0, 20.0),
                "base_complexity": 8.7,
                "material_cost_range": (500, 1600),
                "anchor_price_range": (2200, 9500),
                "demand_score": 8.3,
                "seasonality_score": 8.5,
            },
            {
                "product_type": "Handcrafted Leather-Fabric Clutch",
                "material": "Camel Leather, Raw Silk, Brass Rivets, Mirror",
                "technique": "Suf and Mutwa Geometric Counted-Thread Stitch",
                "length_cm": (20.0, 28.0),
                "width_cm": (4.0, 8.0),
                "height_cm": (12.0, 18.0),
                "weight_kg": (0.25, 0.5),
                "labor_days": (3.0, 9.0),
                "base_complexity": 8.0,
                "material_cost_range": (450, 1100),
                "anchor_price_range": (1600, 5200),
                "demand_score": 8.9,
                "seasonality_score": 8.0,
            },
        ],
    },
    {
        "craft": "Kashmiri Papier-Mâché",
        "state": "Jammu & Kashmir",
        "region": "Kashmir Valley",
        "district": "Srinagar",
        "source_id": "SRC-STATE-05",
        "source_reference": "Handicrafts J&K & Kashmir Papier-Mâché GI-72",
        "products": [
            {
                "product_type": "Decorative Jewellery Box",
                "material": "Mashed Paper Pulp, Starch Paste, 24K Gold Leaf",
                "technique": "Sakhtsazi Moulding and Fine Naqashi Miniature Painting",
                "length_cm": (12.0, 24.0),
                "width_cm": (8.0, 16.0),
                "height_cm": (6.0, 12.0),
                "weight_kg": (0.2, 0.7),
                "labor_days": (3.5, 12.0),
                "base_complexity": 8.4,
                "material_cost_range": (350, 1300),
                "anchor_price_range": (1400, 5800),
                "demand_score": 8.2,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Ornamental Samovar / Vase",
                "material": "Paper Pulp Core, Natural Gums, Varnish Coat",
                "technique": "Gul-i-Wilayat (Floral Arabesque) Golden Naqashi",
                "length_cm": (15.0, 30.0),
                "width_cm": (15.0, 30.0),
                "height_cm": (25.0, 55.0),
                "weight_kg": (0.7, 2.4),
                "labor_days": (5.0, 18.0),
                "base_complexity": 8.8,
                "material_cost_range": (700, 2400),
                "anchor_price_range": (2800, 12500),
                "demand_score": 7.8,
                "seasonality_score": 6.5,
            },
        ],
    },
    {
        "craft": "Kashmiri Carpets",
        "state": "Jammu & Kashmir",
        "region": "Kashmir Valley",
        "district": "Srinagar",
        "source_id": "SRC-STATE-05",
        "source_reference": "Handicrafts J&K & Kashmir Hand-Knotted Carpet GI-74",
        "products": [
            {
                "product_type": "Silk-on-Silk Hand-knotted Carpet (3x5 ft)",
                "material": "Pure Mulberry Silk Pile on Mulberry Silk Warp",
                "technique": "Hand-knotted Talim Script Weaving (500+ KPSI)",
                "length_cm": (150.0, 160.0),
                "width_cm": (90.0, 100.0),
                "height_cm": (0.8, 1.2),
                "weight_kg": (3.5, 6.0),
                "labor_days": (60.0, 180.0),
                "base_complexity": 9.8,
                "material_cost_range": (14000, 38000),
                "anchor_price_range": (45000, 185000),
                "demand_score": 7.2,
                "seasonality_score": 8.0,
            },
            {
                "product_type": "Woolen Persian Motif Rug (4x6 ft)",
                "material": "Highland Merino Wool on Cotton Foundation",
                "technique": "Sennah Knot Single Warp Knotting (250 KPSI)",
                "length_cm": (180.0, 190.0),
                "width_cm": (120.0, 130.0),
                "height_cm": (1.0, 1.5),
                "weight_kg": (6.5, 11.0),
                "labor_days": (35.0, 90.0),
                "base_complexity": 9.2,
                "material_cost_range": (7000, 18000),
                "anchor_price_range": (22000, 68000),
                "demand_score": 7.6,
                "seasonality_score": 8.5,
            },
        ],
    },
    {
        "craft": "Banarasi Handloom",
        "state": "Uttar Pradesh",
        "region": "Purvanchal",
        "district": "Varanasi",
        "source_id": "SRC-GOI-02",
        "source_reference": "DC (Handlooms) & Banaras Brocades GI-99",
        "products": [
            {
                "product_type": "Katan Silk Kadhwa Saree",
                "material": "Pure Katan Mulberry Silk and Gold/Silver Zari",
                "technique": "Kadhwa Handloom Brocade Weaving (Jacquard/Drawloom)",
                "length_cm": (550.0, 630.0),
                "width_cm": (114.0, 120.0),
                "height_cm": (0.1, 0.3),
                "weight_kg": (0.6, 1.1),
                "labor_days": (15.0, 45.0),
                "base_complexity": 9.4,
                "material_cost_range": (4500, 14000),
                "anchor_price_range": (12500, 65000),
                "demand_score": 9.2,
                "seasonality_score": 9.5,
            },
            {
                "product_type": "Georgette Jangla Saree",
                "material": "Pure Silk Georgette and Tested Zari Metallic Thread",
                "technique": "Jangla All-over Floral Vine Weaving",
                "length_cm": (550.0, 630.0),
                "width_cm": (110.0, 118.0),
                "height_cm": (0.1, 0.25),
                "weight_kg": (0.5, 0.8),
                "labor_days": (10.0, 30.0),
                "base_complexity": 9.0,
                "material_cost_range": (3200, 8500),
                "anchor_price_range": (9500, 38000),
                "demand_score": 9.0,
                "seasonality_score": 9.2,
            },
            {
                "product_type": "Brocade Silk Dupatta",
                "material": "Organza Silk and Golden Zari",
                "technique": "Cutwork Handloom Weft Brocade",
                "length_cm": (225.0, 250.0),
                "width_cm": (90.0, 105.0),
                "height_cm": (0.1, 0.2),
                "weight_kg": (0.25, 0.45),
                "labor_days": (4.0, 12.0),
                "base_complexity": 8.2,
                "material_cost_range": (1400, 3500),
                "anchor_price_range": (3800, 14500),
                "demand_score": 8.8,
                "seasonality_score": 9.0,
            },
        ],
    },
    {
        "craft": "Kanjeevaram Silk",
        "state": "Tamil Nadu",
        "region": "Thondaimandalam",
        "district": "Kanchipuram",
        "source_id": "SRC-GOI-02",
        "source_reference": "DC (Handlooms) & Kancheepuram Silk GI-6",
        "products": [
            {
                "product_type": "Korvai Bridal Silk Saree",
                "material": "3-Ply Mulberry Silk Yarn and Silver-Gold Electroplated Zari",
                "technique": "Korvai Interlocking Weft and Petni Temple Border",
                "length_cm": (550.0, 630.0),
                "width_cm": (118.0, 125.0),
                "height_cm": (0.2, 0.4),
                "weight_kg": (0.7, 1.3),
                "labor_days": (12.0, 40.0),
                "base_complexity": 9.5,
                "material_cost_range": (6000, 18000),
                "anchor_price_range": (16000, 85000),
                "demand_score": 9.4,
                "seasonality_score": 9.8,
            },
            {
                "product_type": "Traditional Border Pavada Set",
                "material": "Heavy Silk Warp and Pure Zari Motifs",
                "technique": "Two-Weaver Pit Loom Korvai",
                "length_cm": (280.0, 320.0),
                "width_cm": (90.0, 110.0),
                "height_cm": (0.15, 0.3),
                "weight_kg": (0.45, 0.8),
                "labor_days": (7.0, 20.0),
                "base_complexity": 8.8,
                "material_cost_range": (3200, 8500),
                "anchor_price_range": (8500, 32000),
                "demand_score": 8.8,
                "seasonality_score": 9.2,
            },
        ],
    },
    {
        "craft": "Bamboo Craft",
        "state": "Assam",
        "region": "Brahmaputra Valley",
        "district": "Barpeta",
        "source_id": "SRC-GOI-03",
        "source_reference": "TRIFED & Assam Cane and Bamboo Products",
        "products": [
            {
                "product_type": "Handwoven Storage Basket",
                "material": "Bhaluka Bamboo and Cane Strips",
                "technique": "Fine Hexagonal and Diagonal Splint Weaving",
                "length_cm": (25.0, 50.0),
                "width_cm": (25.0, 50.0),
                "height_cm": (25.0, 60.0),
                "weight_kg": (0.5, 1.8),
                "labor_days": (1.0, 3.5),
                "base_complexity": 4.8,
                "material_cost_range": (90, 280),
                "anchor_price_range": (380, 1400),
                "demand_score": 8.0,
                "seasonality_score": 5.5,
            },
            {
                "product_type": "Jaapi Traditional Conical Hat",
                "material": "Tokou Leaves, Bamboo Splits, and Felt Fabric",
                "technique": "Ribbed Bamboo Framing with Leaf Stitching",
                "length_cm": (40.0, 65.0),
                "width_cm": (40.0, 65.0),
                "height_cm": (18.0, 30.0),
                "weight_kg": (0.4, 0.9),
                "labor_days": (1.5, 4.0),
                "base_complexity": 5.5,
                "material_cost_range": (140, 380),
                "anchor_price_range": (550, 2200),
                "demand_score": 7.8,
                "seasonality_score": 7.5,
            },
            {
                "product_type": "Modern Table Lamp",
                "material": "Treated Mature Bamboo Pole and Brass Hardware",
                "technique": "Slit Turning, Heat Bending, and Lacquer Coating",
                "length_cm": (18.0, 28.0),
                "width_cm": (18.0, 28.0),
                "height_cm": (35.0, 55.0),
                "weight_kg": (0.8, 2.0),
                "labor_days": (1.5, 4.5),
                "base_complexity": 6.2,
                "material_cost_range": (280, 750),
                "anchor_price_range": (950, 3200),
                "demand_score": 8.6,
                "seasonality_score": 6.0,
            },
        ],
    },
    {
        "craft": "Cane Craft",
        "state": "Assam",
        "region": "Upper Assam",
        "district": "Dibrugarh",
        "source_id": "SRC-GOI-03",
        "source_reference": "TRIFED & NEDFi Craft Documentation",
        "products": [
            {
                "product_type": "Handcrafted Lounge Chair",
                "material": "Jati Cane Poles and Split Rattan Bindings",
                "technique": "Steam Bending and Interlaced Rattan Weave",
                "length_cm": (60.0, 85.0),
                "width_cm": (60.0, 80.0),
                "height_cm": (75.0, 95.0),
                "weight_kg": (3.8, 7.5),
                "labor_days": (4.0, 10.0),
                "base_complexity": 7.5,
                "material_cost_range": (900, 2400),
                "anchor_price_range": (2800, 9500),
                "demand_score": 8.2,
                "seasonality_score": 6.0,
            },
            {
                "product_type": "Cane Picnic Hamper",
                "material": "Treated Natural Cane and Genuine Leather Straps",
                "technique": "Close-twill Woven Structure with Metal Hinges",
                "length_cm": (35.0, 50.0),
                "width_cm": (25.0, 38.0),
                "height_cm": (20.0, 32.0),
                "weight_kg": (1.0, 2.4),
                "labor_days": (2.0, 5.0),
                "base_complexity": 6.0,
                "material_cost_range": (400, 950),
                "anchor_price_range": (1250, 3900),
                "demand_score": 8.5,
                "seasonality_score": 7.0,
            },
        ],
    },
    {
        "craft": "Wood Carving",
        "state": "Karnataka",
        "region": "Southern Karnataka",
        "district": "Mysuru",
        "source_id": "SRC-STATE-02",
        "source_reference": "Cauvery Handicrafts & Mysore Rosewood Inlay GI-24",
        "products": [
            {
                "product_type": "Rosewood Inlaid Wall Panel",
                "material": "Indian Rosewood (Dalbergia latifolia) and Wood Veneers",
                "technique": "Marquetry Chiselling and Natural Wood Inlay",
                "length_cm": (35.0, 90.0),
                "width_cm": (25.0, 60.0),
                "height_cm": (2.0, 4.5),
                "weight_kg": (1.8, 6.5),
                "labor_days": (4.0, 16.0),
                "base_complexity": 8.5,
                "material_cost_range": (950, 3400),
                "anchor_price_range": (3200, 15500),
                "demand_score": 8.0,
                "seasonality_score": 6.5,
            },
            {
                "product_type": "Intricately Carved Elephant Figurine",
                "material": "Single Block Teakwood / Rosewood",
                "technique": "Under-cut Jali Carving with Pierced Lattice",
                "length_cm": (10.0, 30.0),
                "width_cm": (6.0, 18.0),
                "height_cm": (8.0, 26.0),
                "weight_kg": (0.4, 3.2),
                "labor_days": (3.0, 12.0),
                "base_complexity": 8.2,
                "material_cost_range": (450, 1800),
                "anchor_price_range": (1500, 8500),
                "demand_score": 8.6,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Carved Wooden Partition Screen",
                "material": "Sheesham Wood and Brass Hinges",
                "technique": "Floral Openwork Jali and Relief Panels",
                "length_cm": (150.0, 200.0),
                "width_cm": (3.0, 5.0),
                "height_cm": (170.0, 190.0),
                "weight_kg": (14.0, 28.0),
                "labor_days": (10.0, 28.0),
                "base_complexity": 8.9,
                "material_cost_range": (3500, 9500),
                "anchor_price_range": (11500, 39000),
                "demand_score": 7.8,
                "seasonality_score": 6.0,
            },
        ],
    },
    {
        "craft": "Stone Carving",
        "state": "Odisha",
        "region": "Coastal Odisha",
        "district": "Puri",
        "source_id": "SRC-STATE-04",
        "source_reference": "Utkalika & Odisha Stone Carving GI-117",
        "products": [
            {
                "product_type": "Konark Wheel Replica",
                "material": "Khandolite Sandstone / Soapstone",
                "technique": "Traditional High-Relief Chisel Carving",
                "length_cm": (20.0, 60.0),
                "width_cm": (6.0, 16.0),
                "height_cm": (20.0, 60.0),
                "weight_kg": (2.5, 18.0),
                "labor_days": (4.0, 18.0),
                "base_complexity": 8.6,
                "material_cost_range": (450, 2200),
                "anchor_price_range": (1800, 12500),
                "demand_score": 8.0,
                "seasonality_score": 6.5,
            },
            {
                "product_type": "Dancing Odissi Apsara Sculpture",
                "material": "Soft Soapstone / Kochila Stone",
                "technique": "Free-standing Three-Dimensional Statuary",
                "length_cm": (10.0, 25.0),
                "width_cm": (8.0, 20.0),
                "height_cm": (25.0, 75.0),
                "weight_kg": (1.8, 14.0),
                "labor_days": (5.0, 22.0),
                "base_complexity": 8.8,
                "material_cost_range": (550, 2800),
                "anchor_price_range": (2400, 16000),
                "demand_score": 7.8,
                "seasonality_score": 6.0,
            },
        ],
    },
    {
        "craft": "Brass Craft",
        "state": "Uttar Pradesh",
        "region": "Rohilkhand",
        "district": "Moradabad",
        "source_id": "SRC-GOI-05",
        "source_reference": "CCIC & Moradabad Metal Craft GI-237",
        "products": [
            {
                "product_type": "Engraved Brass Urli / Bowl",
                "material": "Virgin Brass Alloy (Cu-Zn 60:40)",
                "technique": "Sand Casting and Hand Naqshi Etching",
                "length_cm": (22.0, 50.0),
                "width_cm": (22.0, 50.0),
                "height_cm": (8.0, 20.0),
                "weight_kg": (1.2, 5.5),
                "labor_days": (2.0, 6.0),
                "base_complexity": 6.5,
                "material_cost_range": (650, 2600),
                "anchor_price_range": (1750, 7200),
                "demand_score": 9.0,
                "seasonality_score": 9.0,
            },
            {
                "product_type": "Nataraja Idol Sculpture",
                "material": "Solid Brass with Antique Patina",
                "technique": "Investment Casting and Fine File Finishes",
                "length_cm": (15.0, 35.0),
                "width_cm": (6.0, 16.0),
                "height_cm": (20.0, 55.0),
                "weight_kg": (1.5, 8.0),
                "labor_days": (3.0, 10.0),
                "base_complexity": 7.8,
                "material_cost_range": (900, 4200),
                "anchor_price_range": (2600, 13500),
                "demand_score": 8.6,
                "seasonality_score": 8.5,
            },
            {
                "product_type": "Moroccan Lantern",
                "material": "Sheet Brass and Tinted Glass Panes",
                "technique": "Die-cut Pierced Jali and Soldered Assembly",
                "length_cm": (14.0, 25.0),
                "width_cm": (14.0, 25.0),
                "height_cm": (28.0, 60.0),
                "weight_kg": (0.8, 2.6),
                "labor_days": (1.5, 5.0),
                "base_complexity": 6.2,
                "material_cost_range": (450, 1400),
                "anchor_price_range": (1350, 4600),
                "demand_score": 8.8,
                "seasonality_score": 8.8,
            },
        ],
    },
    {
        "craft": "Bell Metal Craft",
        "state": "Assam",
        "region": "Lower Assam",
        "district": "Barpeta",
        "source_id": "SRC-GOI-01",
        "source_reference": "Sarthebari Bell Metal GI-144 & DC (Handicrafts)",
        "products": [
            {
                "product_type": "Assamese Traditional Xorai",
                "material": "Bell Metal Alloy (Bronze Cu 78% : Sn 22%)",
                "technique": "Hot Hammer Forging on Anvil and Turning",
                "length_cm": (18.0, 36.0),
                "width_cm": (18.0, 36.0),
                "height_cm": (20.0, 45.0),
                "weight_kg": (1.2, 4.5),
                "labor_days": (2.5, 7.0),
                "base_complexity": 7.5,
                "material_cost_range": (900, 3200),
                "anchor_price_range": (2600, 9500),
                "demand_score": 8.2,
                "seasonality_score": 8.5,
            },
            {
                "product_type": "Kahi Bati Dining Set",
                "material": "Resonant Bell Metal",
                "technique": "Manual Beating and Acid Etched Edging",
                "length_cm": (26.0, 32.0),
                "width_cm": (26.0, 32.0),
                "height_cm": (3.0, 8.0),
                "weight_kg": (0.9, 2.4),
                "labor_days": (1.8, 5.0),
                "base_complexity": 6.8,
                "material_cost_range": (700, 1800),
                "anchor_price_range": (1950, 5800),
                "demand_score": 8.0,
                "seasonality_score": 8.0,
            },
        ],
    },
    {
        "craft": "Metalware",
        "state": "Telangana",
        "region": "Warangal",
        "district": "Jangaon",
        "source_id": "SRC-GOI-04",
        "source_reference": "Pembarthi Metal Craft GI-59",
        "products": [
            {
                "product_type": "Repoussé Brass Wall Shield",
                "material": "Rolled Brass Sheet and Red Lead Pitch",
                "technique": "Embossed Repoussé Chasing and Fine Piercing",
                "length_cm": (30.0, 65.0),
                "width_cm": (30.0, 65.0),
                "height_cm": (4.0, 9.0),
                "weight_kg": (1.5, 5.0),
                "labor_days": (3.0, 11.0),
                "base_complexity": 8.0,
                "material_cost_range": (800, 2600),
                "anchor_price_range": (2600, 9800),
                "demand_score": 7.7,
                "seasonality_score": 7.0,
            },
            {
                "product_type": "Kalasam Temple Finial",
                "material": "Heavy Gauge Brass with Lacquer Seal",
                "technique": "Spinning, Joint Brazing, and Hammer Planishing",
                "length_cm": (18.0, 35.0),
                "width_cm": (18.0, 35.0),
                "height_cm": (30.0, 70.0),
                "weight_kg": (2.2, 7.5),
                "labor_days": (4.0, 12.0),
                "base_complexity": 7.9,
                "material_cost_range": (1200, 3800),
                "anchor_price_range": (3600, 14000),
                "demand_score": 8.0,
                "seasonality_score": 8.5,
            },
        ],
    },
    {
        "craft": "Handwoven Textiles",
        "state": "Odisha",
        "region": "Western Odisha",
        "district": "Bargarh",
        "source_id": "SRC-GOI-02",
        "source_reference": "DC (Handlooms) & Sambalpuri Bandha GI-22",
        "products": [
            {
                "product_type": "Sambalpuri Ikat Silk Saree",
                "material": "Tussar/Mulberry Silk and Natural Fast Dyes",
                "technique": "Double Ikat (Warp and Weft Tie-Dye) Handloom",
                "length_cm": (550.0, 630.0),
                "width_cm": (114.0, 120.0),
                "height_cm": (0.1, 0.25),
                "weight_kg": (0.45, 0.75),
                "labor_days": (12.0, 35.0),
                "base_complexity": 9.2,
                "material_cost_range": (2800, 6500),
                "anchor_price_range": (8500, 28500),
                "demand_score": 8.9,
                "seasonality_score": 8.8,
            },
            {
                "product_type": "Cotton Ikat Dress Material",
                "material": "Mercerized 2/120s Cotton",
                "technique": "Single Ikat Bandha Weft Graphic Weaving",
                "length_cm": (450.0, 500.0),
                "width_cm": (105.0, 115.0),
                "height_cm": (0.1, 0.2),
                "weight_kg": (0.4, 0.65),
                "labor_days": (3.5, 9.0),
                "base_complexity": 7.5,
                "material_cost_range": (700, 1600),
                "anchor_price_range": (2100, 5600),
                "demand_score": 9.0,
                "seasonality_score": 8.0,
            },
        ],
    },
    {
        "craft": "Handloom Products",
        "state": "Madhya Pradesh",
        "region": "Gwalior/Bundelkhand",
        "district": "Ashoknagar",
        "source_id": "SRC-GOI-02",
        "source_reference": "DC (Handlooms) & Chanderi Fabric GI-23",
        "products": [
            {
                "product_type": "Chanderi Silk Cotton Saree",
                "material": "Degummed Raw Silk Warp and Cotton Weft with Tested Zari",
                "technique": "Throw-shuttle Pit Loom with Hand-picked Ashavali Butis",
                "length_cm": (550.0, 630.0),
                "width_cm": (112.0, 118.0),
                "height_cm": (0.1, 0.2),
                "weight_kg": (0.35, 0.55),
                "labor_days": (5.0, 18.0),
                "base_complexity": 8.5,
                "material_cost_range": (1400, 3800),
                "anchor_price_range": (4200, 16500),
                "demand_score": 9.1,
                "seasonality_score": 9.0,
            },
            {
                "product_type": "Pure Silk Chanderi Dupatta",
                "material": "Pure Mulberry Katan Silk and Real Metallic Zari",
                "technique": "Transparent Sheer Organza Weave with Meenakari Borders",
                "length_cm": (230.0, 250.0),
                "width_cm": (85.0, 100.0),
                "height_cm": (0.1, 0.15),
                "weight_kg": (0.18, 0.32),
                "labor_days": (3.5, 10.0),
                "base_complexity": 8.0,
                "material_cost_range": (900, 2400),
                "anchor_price_range": (2800, 9200),
                "demand_score": 8.7,
                "seasonality_score": 8.5,
            },
        ],
    },
    {
        "craft": "Leather Craft",
        "state": "Maharashtra",
        "region": "Western Maharashtra",
        "district": "Kolhapur",
        "source_id": "SRC-GOI-04",
        "source_reference": "Kolhapuri Chappal GI-244 & DC (Handicrafts)",
        "products": [
            {
                "product_type": "Handcrafted Kolhapuri Chappal",
                "material": "Vegetable-tanned Bagda Buffalo Leather and Cotton Cord",
                "technique": "Hard Leather Sole Punching, Skiving, and Braid Stitching",
                "length_cm": (24.0, 32.0),
                "width_cm": (9.0, 13.0),
                "height_cm": (1.5, 3.5),
                "weight_kg": (0.45, 0.85),
                "labor_days": (1.0, 3.5),
                "base_complexity": 6.2,
                "material_cost_range": (350, 900),
                "anchor_price_range": (1100, 3600),
                "demand_score": 8.8,
                "seasonality_score": 8.0,
            },
            {
                "product_type": "Braided Leather Belt",
                "material": "Full-grain Vegetable Tanned Leather and Brass Buckle",
                "technique": "8-Plait Hand Braid and Edge Burnishing",
                "length_cm": (85.0, 120.0),
                "width_cm": (3.0, 4.5),
                "height_cm": (0.3, 0.6),
                "weight_kg": (0.2, 0.4),
                "labor_days": (0.6, 2.0),
                "base_complexity": 5.0,
                "material_cost_range": (220, 550),
                "anchor_price_range": (750, 2200),
                "demand_score": 8.5,
                "seasonality_score": 6.5,
            },
        ],
    },
    {
        "craft": "Pottery",
        "state": "Uttar Pradesh",
        "region": "Western UP",
        "district": "Bulandshahr",
        "source_id": "SRC-GOI-04",
        "source_reference": "Khurja Pottery GI-178 & CCIC Catalog",
        "products": [
            {
                "product_type": "Ceramic Dinner Set (18 Pcs)",
                "material": "Stoneware Clay, Feldspar, and Lead-free Glazes",
                "technique": "Slip Casting, High-temperature Tunnel Firing, Decal Print",
                "length_cm": (30.0, 35.0),
                "width_cm": (30.0, 35.0),
                "height_cm": (15.0, 25.0),
                "weight_kg": (6.5, 12.0),
                "labor_days": (3.0, 8.0),
                "base_complexity": 6.8,
                "material_cost_range": (900, 2600),
                "anchor_price_range": (2600, 8500),
                "demand_score": 9.2,
                "seasonality_score": 8.0,
            },
            {
                "product_type": "Hand-painted Ceramic Teapot",
                "material": "Stoneware Body and Cobalt Blue Glaze",
                "technique": "Jigger-Jolly Turning and Underglaze Brushwork",
                "length_cm": (18.0, 26.0),
                "width_cm": (12.0, 18.0),
                "height_cm": (14.0, 22.0),
                "weight_kg": (0.7, 1.6),
                "labor_days": (1.2, 3.5),
                "base_complexity": 5.5,
                "material_cost_range": (250, 650),
                "anchor_price_range": (850, 2600),
                "demand_score": 8.7,
                "seasonality_score": 7.0,
            },
        ],
    },
]

SKILL_LEVELS = [
    {
        "level": "Apprentice",
        "wage_multiplier": 0.85,
        "daily_wage_inr": 450.0,
        "complexity_adj": 0.90,
    },
    {
        "level": "Skilled",
        "wage_multiplier": 1.0,
        "daily_wage_inr": 650.0,
        "complexity_adj": 1.0,
    },
    {
        "level": "Master Craftsman",
        "wage_multiplier": 1.45,
        "daily_wage_inr": 1100.0,
        "complexity_adj": 1.25,
    },
    {
        "level": "National Awardee",
        "wage_multiplier": 2.20,
        "daily_wage_inr": 1800.0,
        "complexity_adj": 1.55,
    },
]

MARKET_CHANNELS = [
    {
        "channel": "Artisan Direct",
        "markup_multiplier": 1.18,
        "overhead_percent": 0.08,
    },
    {
        "channel": "Cooperative Society",
        "markup_multiplier": 1.30,
        "overhead_percent": 0.12,
    },
    {
        "channel": "State Emporium",
        "markup_multiplier": 1.48,
        "overhead_percent": 0.18,
    },
    {
        "channel": "Online Marketplace",
        "markup_multiplier": 1.55,
        "overhead_percent": 0.22,
    },
    {
        "channel": "Luxury Boutique",
        "markup_multiplier": 2.10,
        "overhead_percent": 0.35,
    },
    {
        "channel": "Export",
        "markup_multiplier": 2.45,
        "overhead_percent": 0.40,
    },
]
